#!/bin/bash
# Quick reference for all deployment files
# Run this script to see complete file structure

echo "======================================"
echo "iAcc Deployment Package - File Index"
echo "======================================"
echo ""
echo "📋 MASTER DOCUMENTATION"
echo "├─ DEPLOYMENT_README.md"
echo "│  └─ START HERE: Overview of entire deployment process"
echo "│  └─ Quick start guide"
echo "│  └─ Success indicators"
echo "│  └─ Emergency procedures"
echo ""
echo "├─ DEPLOYMENT_PLAN_STEPS_1-4.md"
echo "│  └─ Complete execution plan for all 4 steps"
echo "│  └─ Timeline and schedule"
echo "│  └─ Risk mitigation strategies"
echo "│  └─ Sign-off checklist"
echo ""
echo "📂 docs/"
echo "├─ STAGING_DEPLOYMENT_GUIDE.md"
echo "│  └─ Step 3: Create staging environment"
echo "│  └─ Subdomain setup (iacc-staging.f2.co.th)"
echo "│  └─ Database cloning"
echo "│  └─ Configuration isolation"
echo "│  └─ Testing procedures"
echo "│  └─ Environment variables"
echo ""
echo "├─ UPGRADE_PHP_MYSQL.md"
echo "│  └─ Step 2: Upgrade to PHP 8.3 & MySQL 8.0"
echo "│  └─ Pre-upgrade backup procedures"
echo "│  └─ EasyApache upgrade steps"
echo "│  └─ MySQL upgrade steps"
echo "│  └─ Post-upgrade verification"
echo "│  └─ Rollback procedures"
echo "│  └─ Monitoring guide"
echo ""
echo "├─ TESTING_CHECKLIST.md"
echo "│  └─ Step 4: Comprehensive testing"
echo "│  └─ 86 test items across 13 sections"
echo "│  ├─ System infrastructure (4 tests)"
echo "│  ├─ Authentication (6 tests)"
echo "│  ├─ Core modules (30 tests)"
echo "│  ├─ PDF generation with logos (15 tests) ⚠️ CRITICAL"
echo "│  ├─ File operations (9 tests)"
echo "│  ├─ Database operations (9 tests)"
echo "│  ├─ Performance (4 tests)"
echo "│  ├─ Security (12 tests)"
echo "│  ├─ Error handling (8 tests)"
echo "│  ├─ PHP 8.3 compatibility (6 tests)"
echo "│  ├─ MySQL 8.0 compatibility (6 tests)"
echo "│  ├─ Deployment verification (5 tests)"
echo "│  └─ Sign-off (5 tests)"
echo ""
echo "📂 backup/"
echo "├─ backup.sh"
echo "│  └─ Automated backup script"
echo "│  └─ Creates: database_*.sql.gz, upload_*.tar.gz, app_*.tar.gz"
echo "│  └─ Retention: Last 10 backups"
echo "│  └─ Logging: Detailed log files"
echo ""
echo "└─ restore.sh"
echo "   └─ Database restoration script"
echo "   └─ Restore from specific backup date"
echo "   └─ Confirmation prompts"
echo ""
echo "📂 scripts/"
echo "├─ deploy-production.sh"
echo "│  └─ Automated production deployment"
echo "│  └─ Pre-deployment backups"
echo "│  └─ Git pull from main branch"
echo "│  └─ Permission fixing"
echo "│  └─ Service restart"
echo "│  └─ Health check"
echo "│  └─ Detailed logging"
echo ""
echo "└─ rollback.sh"
echo "   └─ Emergency rollback script"
echo "   └─ Restore database from backup"
echo "   └─ Restore files from backup"
echo "   └─ Service restart"
echo "   └─ Verification"
echo ""
echo "📂 iacc/inc/"
echo "└─ env-detect.php"
echo "   └─ Environment detection system"
echo "   └─ Auto-detects: staging vs production vs local"
echo "   └─ Loads environment-specific config"
echo "   └─ Database: iacc_database vs iacc_staging"
echo "   └─ Debug mode: ON for staging, OFF for production"
echo "   └─ Labels: RED (prod), ORANGE (staging), BLUE (local)"
echo ""
echo "======================================"
echo "DEPLOYMENT EXECUTION ORDER"
echo "======================================"
echo ""
echo "1️⃣  PRE-DEPLOYMENT (30 min)"
echo "   ├─ Read: DEPLOYMENT_README.md"
echo "   ├─ Read: DEPLOYMENT_PLAN_STEPS_1-4.md"
echo "   └─ Execute: backup/backup.sh"
echo ""
echo "2️⃣  UPGRADE INFRASTRUCTURE (2-3 hours)"
echo "   ├─ Follow: docs/UPGRADE_PHP_MYSQL.md"
echo "   ├─ Upgrade PHP to 8.3 (45 min)"
echo "   ├─ Upgrade MySQL to 8.0 (45 min)"
echo "   └─ Verify: All systems working (20 min)"
echo ""
echo "3️⃣  SETUP STAGING (1-2 hours)"
echo "   ├─ Follow: docs/STAGING_DEPLOYMENT_GUIDE.md"
echo "   ├─ Create: iacc-staging.f2.co.th subdomain"
echo "   ├─ Clone: Production database to iacc_staging"
echo "   ├─ Deploy: Application code to staging"
echo "   └─ Verify: Environment detection working"
echo ""
echo "4️⃣  TEST ON STAGING (1-2 hours)"
echo "   ├─ Access: https://iacc-staging.f2.co.th"
echo "   ├─ Run: docs/TESTING_CHECKLIST.md (86 tests)"
echo "   ├─ Critical: PDF logo display tests ✓"
echo "   ├─ Verify: No errors in logs"
echo "   └─ Sign-off: Testing complete"
echo ""
echo "5️⃣  DEPLOY TO PRODUCTION (1 hour)"
echo "   ├─ Execute: scripts/deploy-production.sh"
echo "   ├─ Or Manual:"
echo "   │  ├─ cd /public_html/iacc"
echo "   │  ├─ git pull origin main"
echo "   │  ├─ chmod -R 755 ."
echo "   │  ├─ chmod -R 777 upload/"
echo "   │  └─ systemctl restart php-fpm"
echo "   └─ Verify: https://iacc.f2.co.th"
echo ""
echo "6️⃣  MONITOR POST-DEPLOYMENT (24 hours)"
echo "   ├─ Check: Error logs"
echo "   ├─ Monitor: Database performance"
echo "   ├─ Test: All critical functions"
echo "   └─ Confirm: All systems stable"
echo ""
echo "======================================"
echo "CRITICAL FILES & TESTING"
echo "======================================"
echo ""
echo "⚠️  MUST TEST (PDF Generation with Logos)"
echo "   ├─ Tax Invoice PDF with logo ✓"
echo "   ├─ Invoice PDF with logo ✓"
echo "   ├─ Delivery Note PDF with logo ✓"
echo "   ├─ Voucher PDF with logo ✓"
echo "   ├─ Report PDFs with logos ✓"
echo "   └─ Location: docs/TESTING_CHECKLIST.md (15 tests)"
echo ""
echo "⚠️  MUST VERIFY (PHP 8.3 Compatibility)"
echo "   ├─ No deprecated each() function"
echo "   ├─ No deprecated array syntax {}"
echo "   ├─ No mysql_* functions (except wrappers)"
echo "   └─ Location: docs/TESTING_CHECKLIST.md (6 tests)"
echo ""
echo "⚠️  MUST VERIFY (MySQL 8.0 Compatibility)"
echo "   ├─ Connection successful"
echo "   ├─ All queries work"
echo "   ├─ Character encoding: utf8mb4"
echo "   └─ Location: docs/TESTING_CHECKLIST.md (6 tests)"
echo ""
echo "======================================"
echo "EMERGENCY PROCEDURES"
echo "======================================"
echo ""
echo "🚨 IF SOMETHING GOES WRONG:"
echo "   ├─ Check error logs:"
echo "   │  └─ tail -f /public_html/iacc/error_log"
echo "   │  └─ tail -f /var/log/mysql/error.log"
echo "   │  └─ tail -f /var/log/iacc-deploy.log"
echo ""
echo "🚨 QUICK ROLLBACK:"
echo "   └─ cd /public_html/iacc"
echo "   └─ ./scripts/rollback.sh [backup_date]"
echo ""
echo "🚨 RESTORE DATABASE ONLY:"
echo "   └─ cd /backups"
echo "   └─ ./restore.sh database_YYYYMMDD_HHMMSS.sql.gz"
echo ""
echo "======================================"
echo "FILE SUMMARY"
echo "======================================"
echo ""
ls -lh /Volumes/Data/Projects/iAcc-PHP-MVC/ | grep -E "^d|DEPLOYMENT|README"
echo ""
ls -lh /Volumes/Data/Projects/iAcc-PHP-MVC/docs/ 2>/dev/null | grep "\.md"
echo ""
ls -lh /Volumes/Data/Projects/iAcc-PHP-MVC/scripts/ 2>/dev/null | grep "\.sh"
echo ""
ls -lh /Volumes/Data/Projects/iAcc-PHP-MVC/backup/ 2>/dev/null | grep "\.sh"
echo ""
echo "======================================"
echo "✅ DEPLOYMENT PACKAGE COMPLETE"
echo "======================================"
echo ""
echo "Status: READY FOR PRODUCTION DEPLOYMENT"
echo ""
echo "Next Step: Read DEPLOYMENT_README.md"
echo ""
