<?php
/**
 * iACC Template Configuration
 * This file will be auto-generated by the Setup Wizard (setup.php)
 * 
 * DO NOT manually edit — run setup.php to configure.
 */
return [
    'configured'   => false,
    'api_url'      => '',
    'api_key'      => '',
    'api_secret'   => '',
    'company_name' => '',
    'site_title'   => 'My Website',
    'theme_color'  => '#0369a1',
    'currency'     => 'THB',
    'timezone'     => 'Asia/Bangkok',
];
